"""create telemetry and warning tables

Revision ID: c49b199a6ffd
Revises: 
Create Date: 2026-04-14 12:15:39.159576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49b199a6ffd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('drs', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_driver_number'), 'telemetry_records', ['driver_number'], unique=False)
    op.create_index(op.f('ix_telemetry_records_recorded_at'), 'telemetry_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_telemetry_records_session_key'), 'telemetry_records', ['session_key'], unique=False)
    op.create_table('warning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_events_driver_number'), 'warning_events', ['driver_number'], unique=False)
    op.create_index(op.f('ix_warning_events_session_key'), 'warning_events', ['session_key'], unique=False)
    op.create_index(op.f('ix_warning_events_triggered_at'), 'warning_events', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warning_events_triggered_at'), table_name='warning_events')
    op.drop_index(op.f('ix_warning_events_session_key'), table_name='warning_events')
    op.drop_index(op.f('ix_warning_events_driver_number'), table_name='warning_events')
    op.drop_table('warning_events')
    op.drop_index(op.f('ix_telemetry_records_session_key'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_recorded_at'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_driver_number'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    # ### end Alembic commands ###
